organizations:
  ops:
    teams:
      Owners:
        members:
          - khuedoan
    repositories:
      homelab:
        migrate:
          source: https://github.com/khuedoan/blog

users:
  khuedoan:
    repositories:
      blog:
        template: false
        private: false
        migrate:
          source: https://github.com/khuedoan/blog
          mirror:
            enable: true
            interval: 5m
            prune: true

settings: {}
